config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "broadcasts#index"

  get "slack/auth", to: 'slack#auth'
  post "slack/logout", to: 'slack#logout'
  resources :broadcasts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lock.rb
class Lock < ActiveRecord::Base
  establish_connection "#{Rails.env}_flussonic".to_sym

  def start
    Time.at(start_at)
  end

  def finish
    Time.at(end_at)
  end

  def duration
    end_at - start_at
  end
end

app/models/recording.rb
class Recording < ActiveRecord::Base
  establish_connection "#{Rails.env}_flussonic".to_sym
  # belongs_to :stream, primary_key: :stream, foreign_key: :name

  def start
    Time.at(start_at)
  end

  def finish
    Time.at(end_at)
  end

  def duration
    end_at - start_at
  end
end

app/models/slack.rb
class Slack
  def self.client_id
    config[:client_id]
  end

  def self.secret
    config[:secret]
  end

  def self.config
    @config ||= (YAML.load(File.read("slack.conf")).with_indifferent_access || {})
  end
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  establish_connection "#{Rails.env}_flussonic".to_sym
  self.primary_key = "name"
  has_many :recordings, primary_key: :name, foreign_key: :stream
  has_many :locks, primary_key: :name, foreign_key: :stream

  def title
    comment.blank? ? name : comment
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def ensure_logged
    session[:user_id] || render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
  end
end

app/controllers/broadcasts_controller.rb
class BroadcastsController < ApplicationController
  before_action :ensure_logged, only: [:create, :destroy]
  def index
    @streams = Stream.where(provider: "avitube").order("name desc").includes(:recordings).all
  end

  def show
    @stream = Stream.find(params[:id])    

    @streams = Stream.where(provider: "avitube").where("name != ?", @stream.name).order("name desc").includes(:recordings).all
  end

  def create
    stream_params = params[:stream].permit(:comment).merge(name: "a#{Time.now.to_i}", 
      provider: "avitube", publish_enabled: true, dvr: "movies 20G")
    if params[:kind] == "sample"
      stream_params[:urls] = "fake://fake"
    end
    Stream.create(stream_params)
    redirect_to "/"
  end

  def destroy
    @stream = Stream.find(params[:id])
    @stream.destroy
    redirect_to "/"
  end
end

app/controllers/slack_controller.rb
class SlackController < ApplicationController
  def auth
    req = {client_id: Slack.client_id, client_secret: Slack.secret, code: params[:code]}
    uri = URI("https://slack.com/api/oauth.access?#{req.to_query}")
    http = Net::HTTP.new(uri.host, uri.port)
    http.set_debug_output $stderr
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Get.new("#{uri.path}?#{req.to_query}")
    request.add_field('Content-Type', 'application/json')
    request.add_field('Accept', 'application/json')
    res = http.request(request)

    if res.code == "200"
      reply = JSON.parse(res.body).with_indifferent_access
      if reply[:ok]
        # puts reply.inspect
        session[:user_id] = reply[:user][:id]
        session[:user_name] = reply[:user][:name]
        session[:team_id] = reply[:team][:id]
        session[:access_token] = reply[:access_token]
        redirect_to "/"
      end
      reply
    else
      nil
    end

  end

  def logout
    session.delete(:user_id)
    session.delete(:user_name)
    session.delete(:team_id)
    session.delete(:access_token)
    redirect_to "/"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged?
    session[:user_id].present?
  end
end

app/views/application/_header_top.html.erb
<% - if Slack.client_id %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="navbar-nav mr-auto">
      <% -if session[:user_name] %>
        <li class="nav-item">
          <span class="nav-link">Hi, <%= session[:user_name] %></span>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <%= button_to "Logout", "/slack/logout", method: "post", class: "btn btn-info" %>        
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to("https://slack.com/oauth/authorize?#{{scope: "identity.basic", client_id: Slack.client_id, redirect_uri: "http://localhost:3000/slack/auth"}.to_query}") do %>
            <img src="https://api.slack.com/img/sign_in_with_slack.png" />
          <%- end %>
        </li>
      <% end %>
    </ul>
  </nav>
<% end %>

app/views/broadcasts/index.html.erb
<h1>Active broadcasts</h1>

<%- if logged? %>
<div class="row">
  <div class="col-md-4 col-sm-6">
    <%= form_tag "/broadcasts", method: :post do %>
      <div class="input-group">
        <input type="text" class="form-control" name="stream[comment]" placeholder="Comment" />        
      </div>
      <div class="input-group">
        <span class="input-group-btn">
          <button type="submit" name="kind" value="sample" class="btn btn-primary">Sample broadcast</button>
        </span>
        <span class="input-group-btn">
          <button type="submit" name="kind" value="published" class="btn btn-success">Published broadcast</button>
        </span>
      </div>
    <% end %>
  </div>
</div>
<% end %>


<%- 
total_width = 4.hour
total_start = total_width.ago %>
<table class="table">
  <% @streams.each do |stream| %>
  <tr>
    <td style="white-space: nowrap;"><%= link_to(stream.title, broadcast_path(stream.name))%></a></td>
    <td><%= stream.bitrate %>k</td>
    <td><%= stream.lifetime ? Time.at(stream.lifetime/1000).utc.strftime("%H:%M:%S") : "offline" %></td>
    <td style="width: 70%" class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="progress" style="width: 100%">
            <%- last_end = total_start %>
            <% stream.recordings.each do |r| %>
              <%- offset2 = r.start < total_start ? 0 : ((r.start - total_start)*100/total_width).round(2)  %> 
              <%- offset = r.start < last_end ? 0 : ((r.start - last_end)*100/total_width).round(2)  %> 
              <%- width = ((r.finish - (r.start < last_end ? last_end : r.start))*100/total_width).round(2) %>
              <%- last_end = r.finish < last_end ? last_end : r.finish %>
              <% if width > 0 %>
                <div class="progress-bar" style="margin-left: <%= offset %>%; width: <%= width %>%;"></div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <%- if false %>
      <div class="row">
        <div class="col-sm-12">
          <div class="progress" style="width: 100%">
            <%- last_end = total_start %>
            <% stream.locks.each do |r| %>
              <%- offset2 = r.start < total_start ? 0 : ((r.start - total_start)*100/total_width).round(2)  %> 
              <%- offset = r.start < last_end ? 0 : ((r.start - last_end)*100/total_width).round(2)  %> 
              <%- width = ((r.finish - (r.start < last_end ? last_end : r.start))*100/total_width).round(2) %>
              <%- last_end = r.finish < last_end ? last_end : r.finish %>
              <% if width > 0 %>
                <div class="progress-bar" style="margin-left: <%= offset %>%; width: <%= width %>%;"></div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </td>
    <td><%= button_to "delete", "/broadcasts/#{stream.name}", method: :delete %></td>
  <% end %>
</table>

app/views/broadcasts/show.html.erb
<h1><%= @stream.title %></h1>


<% hostname = request.env["SERVER_NAME"] %>

<div class="row">
  <div class="col-lg-9">
    
<%- if @stream.bitrate.to_i > 0 %>
    <div class="row">
      <div class="col-lg-12">
<div id="video" data-url="<%=  "http://#{hostname}:8080/#{@stream.name}?ago=3600"%>" style="width:100%;height:480px"></div>

<script>
  onLoad();
  function onLoad() {
    var url = document.getElementById("video").getAttribute("data-url");
    var params = FlussonicPlayer.parseUrl(url, {parentId: "#video"});

    new FlussonicPlayer(params);
  }
</script>

      </div>
    </div>
<%- end %>        


<% if @stream.urls.blank? %>
    <div class="row">
      <div class="col-sm-4">
        <button type="button" class="btn btn-danger" onclick="startPublish()">Publish</button>
      </div>
      <div class="col-sm-4">
        <span>Publish url: <code>rtmp://<%= hostname %>:1935/static/<%= @stream.name %></code></span>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-10">
        <video id="publisher"></video>
      </div>
    </div>
<% end %>


  </div>


  <div class="col-lg-3">
    <%- @streams.each do |stream| %>
    <div class="row">
      <div class="col-lg-12">
        <video style="width:100%" src="//<%= hostname %>:8080/<%= stream.name %>/preview.mp4" ></video>
        <span><%= link_to stream.title, broadcast_path(stream.name) %></span>
      </div>
    </div>
    <%- end %>
  </div> 
</div>


<script type="text/javascript">

function startPublish() {
  initWebRTCVideo("<%= @stream.name %>", document.getElementById("publisher"), function() {
    stopWebRTCVideo();
  }, "http://<%= hostname %>:8080")
}

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Avitube</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="http://demo.flussonic.com/flu/assets/flussonic-player.js"></script>
    <script src="https://unpkg.com/webrtc-adapter@2.0.8/out/adapter.js"></script>
    <!-- <script src="http://localhost:8090/flu/assets/flussonic-player.js"></script> -->
    <!-- <script src="http://0.0.0.0:3001/clappr.min.js"></script>
    <script src="http://0.0.0.0:3001/clappr-stats.js"></script>
    <script src="http://0.0.0.0:3001/level-selector.min.js"></script>
    <script src="http://0.0.0.0:3001/latest/FlussonicPlayer.js"></script> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: "header_top" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>